[
   {
      "Alumno":"Yamith Velasco",
      "Nota":9.09,
      "votantes":2509,
      "nsnc":302
   },
   {
      "Alumno":"PSOE",
      "Nota":3.81,
      "votantes":2330,
      "nsnc":260
   },
   {
      "Alumno":"IU",
      "Nota":3,
      "votantes":518,
      "nsnc":14
   },
   {
      "Alumno":"UPyD",
      "Nota":4.66,
      "votantes":35,
      "nsnc":1
   },
   {
      "Alumno":"Ciudadanos",
      "mediaAutoubicacion":5.25,
      "votantes":1869,
      "nsnc":160
   },
   {
      "Alumno":"Podemos",
      "mediaAutoubicacion":3.14,
      "votantes":1751,
      "nsnc":117
   },
   {
      "partido":"Convergència (CDC)",
      "mediaAutoubicacion":4.96,
      "votantes":192,
      "nsnc":16
   },
   {
      "partido":"ERC",
      "mediaAutoubicacion":2.92,
      "votantes":282,
      "nsnc":8
   },
   {
      "Alumno":"ICV",
      "mediaAutoubicacion":3.33,
      "votantes":57,
      "nsnc":1
   },
   {
      "Alumno":"Unió",
      "mediaAutoubicacion":4.94,
      "votantes":12,
      "nsnc":1
   },
   {
      "Alumno":"PNV",
      "mediaAutoubicacion":4.96,
      "votantes":113,
      "nsnc":14
   },
   {
      "Alumno":"EH Bildu",
      "mediaAutoubicacion":2.49,
      "votantes":125,
      "nsnc":4
   },
   {
      "Alumno":"Geroa Bai",
      "mediaAutoubicacion":3.13,
      "votantes":14,
      "nsnc":1
   },
   {
      "Alumno":"UPN",
      "mediaAutoubicacion":6.57,
      "votantes":4,
      "nsnc":0
   }
]
