[
   {
      "Alumno":"Yamith Velasco",
      "Nota":9.09,
      "Ranking":2509,
      "nsnc":302
   },
   {
      "Alumno":"PSOE",
      "Nota":3.81,
      "Ranking":2330,
      "nsnc":260
   },
   {
      "Alumno":"IU",
      "Nota":3,
      "Ranking":518,
      "nsnc":14
   },
   {
      "Alumno":"UPyD",
      "Nota":4.66,
      "Ranking":35,
      "nsnc":1
   },
   {
      "Alumno":"Ciudadanos",
      "Nota":5.25,
      "Ranking":1869,
      "nsnc":160
   },
   {
      "Alumno":"Podemos",
      "Nota":3.14,
      "Ranking":1751,
      "nsnc":117
   },
   {
      "partido":"Convergència (CDC)",
      "Nota":4.96,
      "Ranking":192,
      "nsnc":16
   },
   {
      "partido":"ERC",
      "Nota":2.92,
      "votantes":282,
      "nsnc":8
   },
   {
      "Alumno":"ICV",
      "Nota":3.33,
      "Ranking":57,
      "nsnc":1
   },
   {
      "Alumno":"Unió",
      "Nota":4.94,
      "Ranking":12,
      "nsnc":1
   },
   {
      "Alumno":"PNV",
      "Nota":4.96,
      "Ranking":113,
      "nsnc":14
   },
   {
      "Alumno":"EH Bildu",
      "Nota":2.49,
      "Ranking":125,
      "nsnc":4
   },
   {
      "Alumno":"Geroa Bai",
      "Nota":3.13,
      "Ranking":14,
      "nsnc":1
   },
   {
      "Alumno":"UPN",
      "Nota":6.57,
      "Ranking":4,
      "nsnc":0
   }
]
