[{"alumno":"Yamith","nota":10,"ranking":10},
{"alumno":"Miriam","nota":5,"ranking":150},
{"alumno":"Alvaro","nota":3,"ranking":15},
{"alumno":"Arturo","nota":3,"ranking":200},
{"alumno":"Samantha","nota":10,"ranking":50},
{"alumno":"Nicole","nota":10"ranking":30},
{"alumno":"Ibeth","nota":2,"ranking":20},
{"alumno":"Mercedes","nota":1,"ranking":80},
{"alumno":"Leidy","nota":4,"ranking":180}]
